# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-26 23:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log_reg', '0001_initial'),
        ('wish_items', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wish',
            name='users',
            field=models.ManyToManyField(blank=True, null=True, related_name='user_wishes', to='log_reg.User'),
        ),
    ]
