# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-27 19:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wish_items', '0002_wish_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wish',
            name='users',
            field=models.ManyToManyField(related_name='user_wishes', to='log_reg.User'),
        ),
    ]
